nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Welcome to our mobile catalogue!
            version: 1.0.0
        paths:
            /bilemo/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Get the JWT token to authenticate
                    requestBody:
                        description: Create a new JWT token
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Get the JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: guy93@rousset.com
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
                        - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/bilemo(?!/doc$) # Accepts routes under /bilemo except /bilemo/doc
